### ISSUE TITLE
Model API Design

### ISSUE THREAD

**Issue by fyu** [SysCV/vis4d#75]
This PR will be a major revision to the API of Vis4D. The core features we implement are:
* A general `BaseDataset` class which replaces `BaseDatasetLoader`, `BaseMapper` and `ScalabelDataset`
	* Support for arbitrary single / multi-sensor configurations
	* Easy customization
* While Scalabel format will stiill be supported for both single / multi-sensor datasets incl evaluation / visualization, it won't be mandatory anymore, i.e. mapping from the input data format directly to Vis4D and back will be possible.
* New tensor-centric data structures: Classes such as `InputSample`, `Boxes2D`, `PointCloud`, etc. will be removed in favor of lightweight TypedDicts
* New tensor-centric model components: Since we remove the current data structures in favor of dicts containing tensors, we rewrite the model API to a tensor-based one too, increasing interoperability with other codebases
* Decoupling of `LightingModule` and model components: We keep the model implementation and the optimization loop separate for the same goal of interoperability, s.t. model components can be used independently of Vis4D / PyTorchLightning

# Roadmap

vis4d.struct:
- [x] Define new TypedDict-based structures: `InputSample`, `Targets`, `Boxes3D`, etc. 
- [x] rewrite utility functions of existing data types (e.g. `Boxes2D.area/center`, ...)

vis4d.data
- [x] Merge `BaseMapper`, `BaseDatasetLoader`, `ScalabelDataset` into `BaseDataset`
- [x] Define API for `BaseDataset` extending `torch.data.Dataset`, supporting:
	- [x] load dataset into a list of dictionaries used to load a single sample
	- [x] function to load single sample into Vis4D format
	- [x] convert predictions from vis4d to dataset format and save
	- [x] evaluate with dataset specific metrics
	- [x] visualize predictions
- [x] Move scalabel util functions for conversion/evaluation/visualization into `datasets.scalabel`
- [x] Adjust `ReferenceSampler`, callbacks, handler, module to new `BaseDataset`

vis4d.model
- [x] Decouple high-level modules (`QDTrack`, `QD3DT`, etc) from `LightningModule`
- [x] All components inherit directly from `nn.Module`
- [x] rewrite API for each module to Tensor-in / Tensor-out (or Dict / List of those), to enable e.g. ONNX export & interoperability with other PyTorch based libraries
- [x] decouple network execution from post-processing (e.g. don't return processed `Boxes2D` directly, but return network out, and have separate post-processing function)

vis4d.common
- [x] Remove `Vis4DModule` in favor of directly inheriting from `nn.Module`
- [x] Adjust existing components (e.g. box sampler / matcher / pooler) to new data types

vis4d.vis
- [x] Adjust visualization functions to new data types

vis4d.projects
- [x] Adjust existing projects to new API
- [x] Move projects into main package
